### ISSUE TITLE
Sintesis

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/sintesis-MaGuadalupeQuiroz#2]
[Sintesis.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-MaGuadalupeQuiroz/files/7148820/Sintesis.pdf)

**Comment by Jaci14** [comment]
La información es breve y precisa, e resume adecuadamente el video de la "web binar", relaciona las ideas entre sí en un solo texto y la síntesis cumple con los criterios de diseños planteados. 

calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
